import { Component, OnInit , Input, HostListener} from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { HttpHeaders } from '@angular/common/http';
import { Router} from '@angular/router';
import { ViewportScroller } from "@angular/common";
import { FormGroup, FormControl, Validators, FormBuilder, FormArray} from '@angular/forms';

import { msginLogConsole } from '../consoleLog';
import { LoginIdentif } from '../JsonServerClass';

import { environment } from 'src/environments/environment';
import { EventAug } from '../JsonServerClass';
import { EventCommentStructure } from '../JsonServerClass';
import { TableOfEventLogin } from '../JsonServerClass';
import { BucketList } from '../JsonServerClass';
import { Bucket_List_Info } from '../JsonServerClass';
import { OneBucketInfo } from '../JsonServerClass';
import { msgConsole } from '../JsonServerClass';

@Component({
  selector: 'app-AdminConsole',
  templateUrl: './AdminConsole.component.html',
  styleUrls: ['./AdminConsole.component.css']
})

export class AdminConsoleComponent {

  
  constructor(
    private router:Router,
    private http: HttpClient,
    private scroller: ViewportScroller

    ) {}

    
    @Input() theReceivedData=new Array<msgConsole>();

    ContentTodisplay:boolean=false;


ngOnInit(){
  
  // the list of all objects from console is generated by module ListBucketContent
  // then all messages are displayed from table 'this.theReceivedData'
  ///////////////////////////////////////////////////////

  // use the service ManageMongoDB to get the list of the console message in ListBucketContent


      this.scroller.scrollToAnchor('targetTop');
      this.ContentTodisplay=true;

  }    


}